reticulate::py_install("pandas")
require(reticulate)
py_require("pandas")
py_install("pandas")
reticulate::py_install('ucimlrepo')
Sys.setenv(RETICULATE_PYTHON = "C:/Users/jhush/Documents/.virtualenvs/r-reticulate/Scripts/python.exe")
